/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxy_CONSTANTS_H
#define proxy_CONSTANTS_H

#include "proxy_types.h"



class proxyConstants {
 public:
  proxyConstants();

};

extern const proxyConstants g_proxy_constants;



#endif
