/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pancake_thrift_response_H
#define pancake_thrift_response_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxy_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class pancake_thrift_responseIf {
 public:
  virtual ~pancake_thrift_responseIf() {}
  virtual void async_get(const sequence_id& seq_id, const std::string& result) = 0;
  virtual void async_put(const sequence_id& seq_id, const std::string& key, const std::string& value) = 0;
  virtual void async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys) = 0;
  virtual void async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values) = 0;
};

class pancake_thrift_responseIfFactory {
 public:
  typedef pancake_thrift_responseIf Handler;

  virtual ~pancake_thrift_responseIfFactory() {}

  virtual pancake_thrift_responseIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(pancake_thrift_responseIf* /* handler */) = 0;
};

class pancake_thrift_responseIfSingletonFactory : virtual public pancake_thrift_responseIfFactory {
 public:
  pancake_thrift_responseIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf>& iface) : iface_(iface) {}
  virtual ~pancake_thrift_responseIfSingletonFactory() {}

  virtual pancake_thrift_responseIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(pancake_thrift_responseIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> iface_;
};

class pancake_thrift_responseNull : virtual public pancake_thrift_responseIf {
 public:
  virtual ~pancake_thrift_responseNull() {}
  void async_get(const sequence_id& /* seq_id */, const std::string& /* result */) {
    return;
  }
  void async_put(const sequence_id& /* seq_id */, const std::string& /* key */, const std::string& /* value */) {
    return;
  }
  void async_get_batch(const sequence_id& /* seq_id */, const std::vector<std::string> & /* keys */) {
    return;
  }
  void async_put_batch(const sequence_id& /* seq_id */, const std::vector<std::string> & /* keys */, const std::vector<std::string> & /* values */) {
    return;
  }
};

typedef struct _pancake_thrift_response_async_get_args__isset {
  _pancake_thrift_response_async_get_args__isset() : seq_id(false), result(false) {}
  bool seq_id :1;
  bool result :1;
} _pancake_thrift_response_async_get_args__isset;

class pancake_thrift_response_async_get_args {
 public:

  pancake_thrift_response_async_get_args(const pancake_thrift_response_async_get_args&);
  pancake_thrift_response_async_get_args& operator=(const pancake_thrift_response_async_get_args&);
  pancake_thrift_response_async_get_args() : result() {
  }

  virtual ~pancake_thrift_response_async_get_args() throw();
  sequence_id seq_id;
  std::string result;

  _pancake_thrift_response_async_get_args__isset __isset;

  void __set_seq_id(const sequence_id& val);

  void __set_result(const std::string& val);

  bool operator == (const pancake_thrift_response_async_get_args & rhs) const
  {
    if (!(seq_id == rhs.seq_id))
      return false;
    if (!(result == rhs.result))
      return false;
    return true;
  }
  bool operator != (const pancake_thrift_response_async_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const pancake_thrift_response_async_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class pancake_thrift_response_async_get_pargs {
 public:


  virtual ~pancake_thrift_response_async_get_pargs() throw();
  const sequence_id* seq_id;
  const std::string* result;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _pancake_thrift_response_async_put_args__isset {
  _pancake_thrift_response_async_put_args__isset() : seq_id(false), key(false), value(false) {}
  bool seq_id :1;
  bool key :1;
  bool value :1;
} _pancake_thrift_response_async_put_args__isset;

class pancake_thrift_response_async_put_args {
 public:

  pancake_thrift_response_async_put_args(const pancake_thrift_response_async_put_args&);
  pancake_thrift_response_async_put_args& operator=(const pancake_thrift_response_async_put_args&);
  pancake_thrift_response_async_put_args() : key(), value() {
  }

  virtual ~pancake_thrift_response_async_put_args() throw();
  sequence_id seq_id;
  std::string key;
  std::string value;

  _pancake_thrift_response_async_put_args__isset __isset;

  void __set_seq_id(const sequence_id& val);

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const pancake_thrift_response_async_put_args & rhs) const
  {
    if (!(seq_id == rhs.seq_id))
      return false;
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const pancake_thrift_response_async_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const pancake_thrift_response_async_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class pancake_thrift_response_async_put_pargs {
 public:


  virtual ~pancake_thrift_response_async_put_pargs() throw();
  const sequence_id* seq_id;
  const std::string* key;
  const std::string* value;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _pancake_thrift_response_async_get_batch_args__isset {
  _pancake_thrift_response_async_get_batch_args__isset() : seq_id(false), keys(false) {}
  bool seq_id :1;
  bool keys :1;
} _pancake_thrift_response_async_get_batch_args__isset;

class pancake_thrift_response_async_get_batch_args {
 public:

  pancake_thrift_response_async_get_batch_args(const pancake_thrift_response_async_get_batch_args&);
  pancake_thrift_response_async_get_batch_args& operator=(const pancake_thrift_response_async_get_batch_args&);
  pancake_thrift_response_async_get_batch_args() {
  }

  virtual ~pancake_thrift_response_async_get_batch_args() throw();
  sequence_id seq_id;
  std::vector<std::string>  keys;

  _pancake_thrift_response_async_get_batch_args__isset __isset;

  void __set_seq_id(const sequence_id& val);

  void __set_keys(const std::vector<std::string> & val);

  bool operator == (const pancake_thrift_response_async_get_batch_args & rhs) const
  {
    if (!(seq_id == rhs.seq_id))
      return false;
    if (!(keys == rhs.keys))
      return false;
    return true;
  }
  bool operator != (const pancake_thrift_response_async_get_batch_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const pancake_thrift_response_async_get_batch_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class pancake_thrift_response_async_get_batch_pargs {
 public:


  virtual ~pancake_thrift_response_async_get_batch_pargs() throw();
  const sequence_id* seq_id;
  const std::vector<std::string> * keys;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _pancake_thrift_response_async_put_batch_args__isset {
  _pancake_thrift_response_async_put_batch_args__isset() : seq_id(false), keys(false), values(false) {}
  bool seq_id :1;
  bool keys :1;
  bool values :1;
} _pancake_thrift_response_async_put_batch_args__isset;

class pancake_thrift_response_async_put_batch_args {
 public:

  pancake_thrift_response_async_put_batch_args(const pancake_thrift_response_async_put_batch_args&);
  pancake_thrift_response_async_put_batch_args& operator=(const pancake_thrift_response_async_put_batch_args&);
  pancake_thrift_response_async_put_batch_args() {
  }

  virtual ~pancake_thrift_response_async_put_batch_args() throw();
  sequence_id seq_id;
  std::vector<std::string>  keys;
  std::vector<std::string>  values;

  _pancake_thrift_response_async_put_batch_args__isset __isset;

  void __set_seq_id(const sequence_id& val);

  void __set_keys(const std::vector<std::string> & val);

  void __set_values(const std::vector<std::string> & val);

  bool operator == (const pancake_thrift_response_async_put_batch_args & rhs) const
  {
    if (!(seq_id == rhs.seq_id))
      return false;
    if (!(keys == rhs.keys))
      return false;
    if (!(values == rhs.values))
      return false;
    return true;
  }
  bool operator != (const pancake_thrift_response_async_put_batch_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const pancake_thrift_response_async_put_batch_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class pancake_thrift_response_async_put_batch_pargs {
 public:


  virtual ~pancake_thrift_response_async_put_batch_pargs() throw();
  const sequence_id* seq_id;
  const std::vector<std::string> * keys;
  const std::vector<std::string> * values;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class pancake_thrift_responseClient : virtual public pancake_thrift_responseIf {
 public:
  pancake_thrift_responseClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  pancake_thrift_responseClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void async_get(const sequence_id& seq_id, const std::string& result);
  void send_async_get(const sequence_id& seq_id, const std::string& result);
  void async_put(const sequence_id& seq_id, const std::string& key, const std::string& value);
  void send_async_put(const sequence_id& seq_id, const std::string& key, const std::string& value);
  void async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys);
  void send_async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys);
  void async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values);
  void send_async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class pancake_thrift_responseProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (pancake_thrift_responseProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_async_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_async_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_async_get_batch(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_async_put_batch(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  pancake_thrift_responseProcessor(::apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> iface) :
    iface_(iface) {
    processMap_["async_get"] = &pancake_thrift_responseProcessor::process_async_get;
    processMap_["async_put"] = &pancake_thrift_responseProcessor::process_async_put;
    processMap_["async_get_batch"] = &pancake_thrift_responseProcessor::process_async_get_batch;
    processMap_["async_put_batch"] = &pancake_thrift_responseProcessor::process_async_put_batch;
  }

  virtual ~pancake_thrift_responseProcessor() {}
};

class pancake_thrift_responseProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  pancake_thrift_responseProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< pancake_thrift_responseIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< pancake_thrift_responseIfFactory > handlerFactory_;
};

class pancake_thrift_responseMultiface : virtual public pancake_thrift_responseIf {
 public:
  pancake_thrift_responseMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~pancake_thrift_responseMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> > ifaces_;
  pancake_thrift_responseMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<pancake_thrift_responseIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void async_get(const sequence_id& seq_id, const std::string& result) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->async_get(seq_id, result);
    }
    ifaces_[i]->async_get(seq_id, result);
  }

  void async_put(const sequence_id& seq_id, const std::string& key, const std::string& value) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->async_put(seq_id, key, value);
    }
    ifaces_[i]->async_put(seq_id, key, value);
  }

  void async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->async_get_batch(seq_id, keys);
    }
    ifaces_[i]->async_get_batch(seq_id, keys);
  }

  void async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->async_put_batch(seq_id, keys, values);
    }
    ifaces_[i]->async_put_batch(seq_id, keys, values);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class pancake_thrift_responseConcurrentClient : virtual public pancake_thrift_responseIf {
 public:
  pancake_thrift_responseConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  pancake_thrift_responseConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void async_get(const sequence_id& seq_id, const std::string& result);
  void send_async_get(const sequence_id& seq_id, const std::string& result);
  void async_put(const sequence_id& seq_id, const std::string& key, const std::string& value);
  void send_async_put(const sequence_id& seq_id, const std::string& key, const std::string& value);
  void async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys);
  void send_async_get_batch(const sequence_id& seq_id, const std::vector<std::string> & keys);
  void async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values);
  void send_async_put_batch(const sequence_id& seq_id, const std::vector<std::string> & keys, const std::vector<std::string> & values);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
